export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

export const GET_BUYER_PROFILE = "GET_BUYER_PROFILE";
export const BUYER_PROFILE_INPUT_CHANGE_HANDLER = "BUYER_PROFILE_INPUT_CHANGE_HANDLER";
export const UPDATE_BUYER_IMAGE= "UPDATE_BUYER_IMAGE";
export const UPDATE_BUYER_PROFILE= "UPDATE_BUYER_PROFILE";

export const GET_OWNER_PROFILE = "GET_OWNER_PROFILE";
export const OWNER_PROFILE_INPUT_CHANGE_HANDLER = "OWNER_PROFILE_INPUT_CHANGE_HANDLER";
export const UPDATE_OWNER_IMAGE= "UPDATE_OWNER_IMAGE";
export const UPDATE_OWNER_PROFILE= "UPDATE_OWNER_PROFILE";

export const GET_RESTAURANT_PROFILE = "GET_RESTAURANT_PROFILE";
export const RESTAURANT_PROFILE_INPUT_CHANGE_HANDLER = "RESTAURANT_PROFILE_INPUT_CHANGE_HANDLER";
export const UPDATE_RESTAURANT_IMAGE= "UPDATE_RESTAURANT_IMAGE";
export const UPDATE_RESTAURANT_PROFILE= "UPDATE_RESTAURANT_PROFILE";

export const GET_OWNER_ORDERS = "GET_OWNER_ORDERS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const GET_BUYER_PAST_ORDERS = "GET_BUYER_PAST_ORDERS";
export const UPDATE_PAST_ORDER_SUCCESS = "UPDATE_PAST_ORDER_SUCCESS";
export const GET_BUYER_UPCOMING_ORDERS = "GET_BUYER_UPCOMING_ORDERS";
export const UPDATE_UPCOMING_ORDER_SUCCESS = "UPDATE_UPCOMING_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED";

export const GET_SECTIONS = "GET_SECTIONS";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";
export const ADD_SECTION_FAILED = "ADD_SECTION_FAILED";
export const SECTION_INPUT_CHANGE_HANDLER = "SECTION_INPUT_CHANGE_HANDLER";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";
export const DELETE_SECTION_FAILED = "DELETE_SECTION_FAILED";